name: Deploy Project C 
on: 
  push: 
    branches: [ "main" ] 
jobs: 
  deploy: 
    uses: kampalalove/ogencomplex/.github/workflows/deploy.yml@master 
    with: 
      project-name: project-c 
      environment: production 
